title: A.M.
description: Writing about cybersecurity, risk, and resilient security architecture.
url: "https://amahmud01.github.io"
baseurl: "/blog"
permalink: /:year/:month/:day/:title/
markdown: kramdown
show_excerpts: true
