title: A.M.
description: Writing about security, risk, and how things actually break.
url: "https://am-netizen.github.io"
baseurl: "/locus"
permalink: /:year/:month/:day/:title/
markdown: kramdown
show_excerpts: true
